export const DummyMain = [
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업", // 사업명
    progress: "착수신고", // 사업 진행
    total_target: 0, // 토탈 목표
    total_current: 0, // 토탈 현재
    company_count: 2, // 묶음 사업의 업체 수
    child_count: 1, // 묶음 사업의 대표업체 제외 업체 수
    main_company: "동화정밀공업 미음지점",
    company: [
      {
        name: "동화정밀공업 미음지점", // 기업명
        main: true, // 대표업체 확인
        tax: "606-81-82037", // 사업자 번호
        biz_num: "180111-0456392", // 법인 번호
        address: "부산광역시 강서구 미음국제로4로 94", // 기업주소
        lat: "", // 위도
        lng: "", // 경도
        progress: "착수신고", // 사업진행
        count: 2, // 공기압축기 수
        target: 700, // 목표
        current: 130, // 현재
      },
      {
        name: "주식회사 동화정밀공업",
        main: false,
        tax: "505-81-03821",
        biz_num: "171211-0003407",
        address: "경상북도 경주시 서면 아화공단길 18",
        address_num: 0,
        progress: "착수신고",
        count: 2,
        target: 300,
        current: 30.75,
      },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "신한단조",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 3,
    child_count: 2,
    main_company: "대연정공",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 5,
    child_count: 4,
    main_company: "신성에스앤티",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "5", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "넥스턴바이오사이언스",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "다스코",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "수성기체산업",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "동산테크",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 5,
    child_count: 4,
    main_company: "대한테크",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "5", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
  {
    biz_name: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 2차",
    total_reduction: 0,
    target_reduction: 0,
    company_count: 4,
    child_count: 3,
    main_company: "덕성인더스트리",
    company: [
      { name: "1", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "2", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "3", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
      { name: "4", address: "부산광역시.....", lat: "위도", lng: "경도", count: 2 },
    ],
  },
];

export const DummyCompany = [
  {
    name: "동화정밀공업 미음지점",
    address: "부산광역시 강서구 미음국제로4로 94",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "착수신고",
    count: 2,
    total_time: 18470,
    run_time: 17220,
    specific_power: 0.0898,
    max_flow_rate: 6.87,
    tax: "606-81-82037",
    biz_num: "180111-0456392",
  },
  {
    name: "㈜ 신한단조",
    address: "부산광역시 강서구 녹산산업북고313번길 21",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 20123,
    run_time: 19765,
    specific_power: 0.0828,
    max_flow_rate: 15.09,
    tax: "606-81-23891",
    biz_num: "180111-0288349",
  },
  {
    name: "우성기업",
    address: "부산광역시 사하구 다산로208번길 7",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 14500,
    run_time: 13645,
    specific_power: 0.0811,
    max_flow_rate: 11.3,
    tax: "606-12-95216",
    biz_num: "-",
  },
  {
    name: "주식회사 우진정기",
    address: "부산광역시 강서구 과학산단로 495",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 16890,
    run_time: 16200,
    specific_power: 0.101,
    max_flow_rate: 12.38,
    tax: "743-86-02040",
    biz_num: "180111-1406768",
  },
  {
    name: "㈜ 자이언엔텍",
    address: "부산광역시 강서구 가달1로 65",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 23300,
    run_time: 22100,
    specific_power: 0.0786,
    max_flow_rate: 15.9,
    tax: "606-86-39438",
    biz_num: "180111-0819459",
  },
  {
    name: "주식회사 하트만",
    address: "부산광역시 강서구 낙동남로 533번길 53",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 18700,
    run_time: 17900,
    specific_power: 0.0898,
    max_flow_rate: 6.87,
    tax: "603-81-40173",
    biz_num: "180111-0305325",
  },
  {
    name: "주식회사 대연정공",
    address: "경상남도 진주시 솔밭로44번길 9",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    count: 1,
    total_time: 22300,
    run_time: 21900,
    specific_power: 0.0811,
    max_flow_rate: 11.3,
    tax: "613-81-10884",
    biz_num: "191111-0010848",
  },
  {
    name: "J. T. C (제이티씨)",
    address: "경상남도 사천시 축동면 오리동길 155-39",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    count: 1,
    total_time: 16000,
    run_time: 15250,
    specific_power: 0.0828,
    max_flow_rate: 15.09,
    tax: "613-22-94214",
    biz_num: "-",
  },
  {
    name: "주식회사 효정산업",
    address: "경상남도 사천시 축동면 서상로 1189",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서보완 3차",
    count: 1,
    total_time: 25000,
    run_time: 24300,
    specific_power: 0.0786,
    max_flow_rate: 15.9,
    tax: "613-81-45874",
    biz_num: "191111-0041017",
  },
  {
    name: "신성에스앤티주식회사",
    address: "대구광역시 당성군 다사읍 세천로3길 10",
    address_num: 0,
    business: "고효율 공기압축기 교체를 통한 온실가스 감축사업",
    progress: "문서재제출 1차",
    count: 1,
    total_time: 17200,
    run_time: 16580,
    specific_power: 0.101,
    max_flow_rate: 12.38,
    tax: "514-81-71890",
    biz_num: "170111-0399320",
  },
];

export const DummyList = [
  {
    date: "2025-01-01",
    name: "김영철",
    total_time: 17200,
    run_time: 16580,
    specific_power: 0.0894,
    max_flow_rate: 6.9,
  },
  {
    date: "2025-01-15",
    name: "김영철",
    total_time: 16000,
    run_time: 15250,
    specific_power: 0.0828,
    max_flow_rate: 15.09,
  },
  {
    date: "2025-01-21",
    name: "김영철",
    total_time: 14500,
    run_time: 13645,
    specific_power: 0.0811,
    max_flow_rate: 11.3,
  },
];

export const DummyComp = [
  { img: "/img/comp/GA37.png", maker: "Atlas Copco", name: "GA37VSD+(1호기)", serial: "WUX383352", year: "2019", hp: 50, power_use: 0.0898, flow_min: 6.87 },
  { img: "/img/comp/GA37.png", maker: "Atlas Copco", name: "GA37VSD+(2호기)", serial: "WUX383748", year: "2019", hp: 50, power_use: 0.0898, flow_min: 6.87 },
  { img: "/img/comp/GA55.png", maker: "Atlas Copco", name: "GA55VSD+", serial: "API863186", year: "2019", hp: 75, power_use: 0.0811, flow_min: 11.3 },
];

// total_time: 18470,
// run_time: 17220,
// specific_power: 0.0898,
// max_flow_rate: 6.87,
export const DummyReportChart = [
  { date: "01", data: 28.68 },
  { date: "02", data: 33.45 },
  { date: "03", data: 31.22 },
  { date: "04", data: 27.8 },
  { date: "05", data: 34.91 },
  { date: "06", data: 30.18 },
  { date: "07", data: 35.66 },
  { date: "08", data: 32.75 },
  { date: "09", data: 29.88 },
  { date: "10", data: 36.11 },
  { date: "11", data: 26.74 },
  { date: "12", data: 33.07 },
].map((item) => {
  const total_elec = Number(((item.data * 1000) / 0.4781).toFixed(2));
  const total_air = Number((total_elec / 0.0898).toFixed(2));
  const total_time = Number((total_air / 6.87).toFixed(2));
  return {
    ...item,
    total_elec,
    total_air,
    total_time,
  };
});

export const dum_company = [
  {
    name: "업체명",
    comp: [
      {
        comp_idx: 222,
        comp_name: "압축기1",
        serial_number: "SN123456",
        model: "ModelX",
        maker: "아틀라스",
        make_year: 2020,
        hp: 100,
        kw_by_flow: 10.5,
        max_output: 100,
        write_date: "2023-10-01",
      },
    ],
  },
];
